# Generated by Django 5.0.3 on 2024-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_email_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email_is_validated',
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
