# Generated by Django 5.0.3 on 2024-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_email_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email_is_validated',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
