# Generated by Django 5.0.3 on 2024-04-04 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
