# Generated by Django 5.0.3 on 2024-04-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='store_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
